# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sum_of_squares <- function(mat) {
    .Call(`_fastMN_sum_of_squares`, mat)
}

